autonomy_level: L1
context:
  files_limit: 120
  exclude:
    - ".venv/**"
    - "node_modules/**"
    - "**/__pycache__/**"

# Blueprint/Task planning configuration
blueprint:
  enabled: true
  # Directory for task definitions (relative to project root)
  dir: "docs/por/blueprint"
  # Maximum steps per task (2-8)
  max_steps: 8
  # Require scope.yaml for task planning
  require_scope: false
  # Auto-complete tasks when all steps done
  auto_complete: true
  # Log progress markers to ledger
  log_to_ledger: true

handoff_filter:
  enabled: true
  cooldown_seconds: 15
  min_chars: 40
  min_words: 6
  # Long-text redundancy suppression: drop highly similar long content without new EVIDENCE/QUESTION
  redundant_window_seconds: 120
  redundant_similarity_threshold: 0.9
  dedup_max_keep: 10
  dedup_short_seconds: 30
  # If none of the following keywords appear and the text is short, treat as low-signal
  require_keywords_any:
    - "CLAIM:"
    - "COUNTER:"
    - "EVIDENCE:"
    - "TASK"
  # High-signal boosters (bypass cooldown when any matches)
  boost_keywords_any:
    - "CLAIM:"
    - "COUNTER:"
    - "EVIDENCE:"
    - "TASK"
  boost_regexes:
    - '```'          # fenced code
  bypass_cooldown_when_high_signal: true
  # Treat as low-signal when any of the following regexes matches (case-insensitive)
  drop_regexes:
    - '^\s*(ok|okay|ready|standby|waiting|idle)\b'
